
  yourGlobalVariable = 0

  $('.col-lg-10 > input').keyup ->
    empty = false
    $('.col-lg-10 > input').each ->
      if $(this).val() == ''
        empty = true
      return
    if empty
      $('#focusedInput').attr 'disabled', 'disabled'
    else
      $('#focusedInput').removeAttr 'disabled'
    return
  $('#focusedInput').keyup ->
    empty = false
    if $(this).val() == ''
      empty = true
    if empty
      document.getElementById('focusedInput').className = 'form-control empty'
    else
      document.getElementById('focusedInput').className = 'form-control'
    return

  $('#focusedInput').keyup (event) ->
    mesString = document.getElementById('focusedInput').value
    email = document.getElementById('inputEmail').value
    if document.getElementById('focusedInput').value != ''

      if event.keyCode == 13

        globalDiv = document.getElementById('omg')
        nameString = document.getElementById('nameInput').value
        
        today = new Date

        dd = today.getDate()
        mm = today.getMonth() + 1
        yyyy = today.getFullYear()

        if dd < 10
          dd = '0' + dd
        if mm < 10
          mm = '0' + mm
        today = dd + '.' + mm + '.' + yyyy
        if yourGlobalVariable > 0
          sep = document.createElement('div')
          sep.setAttribute 'class', 'list-group-separator'
          globalDiv.appendChild sep

        newDiv = document.createElement('div')
        newDiv.setAttribute 'class', 'list-group-item'
        globalDiv.appendChild newDiv

        imgDiv = document.createElement('div')
        imgDiv.setAttribute 'class', 'row-action-primary'
        newDiv.appendChild imgDiv

        img = document.createElement('img')
        img.setAttribute 'class', 'circle'
        gravatar = 'http://www.gravatar.com/avatar/' + CryptoJS.MD5(email)
        img.setAttribute 'src', gravatar
        console.log gravatar
        imgDiv.appendChild img

        contDiv = document.createElement('div')
        contDiv.setAttribute 'class', 'row-content'
        newDiv.appendChild contDiv
        timeDiv = document.createElement('div')

        timeDiv.setAttribute 'class', 'least-content'
        timeDiv.appendChild document.createTextNode(today)
        contDiv.appendChild timeDiv
        nameUser = document.createElement('h4')

        nameUser.setAttribute 'class', 'list-group-item-heading'
        nameUser.appendChild document.createTextNode(nameString)
        contDiv.appendChild nameUser

        mesDiv = document.createElement('p')
        mesDiv.setAttribute 'class', 'list-group-item-text'
        mesDiv.appendChild document.createTextNode(mesString)
        contDiv.appendChild mesDiv

        yourGlobalVariable++

    return
  return

# ---
# generated by js2coffee 2.0.3